export const ADD_INGR = 'ADD_INGR';
export const REMOVE_INGR = 'REMOVE_INGR';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const FILL_INGRS = 'FILL_INGRS';
export const INGRS_LOADING_FAILED = 'INGRS_LOADING_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const MAKE_BURGER_PURCHASE = 'MAKE_BURGER_PURCHASE';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILURE = 'PURCHASE_BURGER_FAILURE';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const GET_ORDERS = 'GET_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const AUTO_SIGN_IN = 'AUTO_SIGN_IN';
export const AUTH_START = 'AUTH_START';
export const AUTH_USER_SAGA = 'AUTH_USER_SAGA';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';